name: Android CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest # Using a Windows runner

    steps:
    # Step 1: Checkout the code
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Step 2: Set up JDK
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    # Step 3: Grant execute permissions for Gradlew
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Step 4: Cache Gradle dependencies
    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # Step 5: Build the project using Gradle
    - name: Build APK
      run: ./gradlew assembleRelease

    # Step 6: Upload the generated APK as an artifact
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release-apk
        path: app/build/outputs/apk/release/*.apk
